=== santaned/EAP/l3/validation/src/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="p">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="class">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="student" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="firstname"/>
                                        <xs:element type="xs:string" name="lastname"/>
                                        <xs:element type="xs:byte" name="age"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:byte" name="id" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== santaned/EAP/l3/validation/src/class.xml
<?xml version="1.0" encoding="UTF-8"?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="schema.xsd">
    <class>
        <student id="1">
            <firstname>Ivan</firstname>
            <lastname>Petrov</lastname>
            <age>20</age>
        </student>
        <student id="2">
            <firstname>Igor</firstname>
            <lastname>Tregulov</lastname>
            <age>22</age>
        </student>
        <student id="3">
            <firstname>Snezhana</firstname>
            <lastname>Vysokova</lastname>
            <age>19</age>
        </student>
    </class>
</p>
